### ISSUE TITLE
hash mismatch error 0.1.13 alby

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#129] opened 2024-09-05 17:29 UTC
possibly related to: #89

**Comment by alltheseas** [comment] 2024-09-05 18:46
![hash mismatch](https://github.com/user-attachments/assets/c1687166-e81e-432c-bcfc-3e12e65ec8d9)

**Comment by franzaps** [comment] 2024-10-04 01:11
Yes duplicate of #89

**Closed by franzaps** 2024-10-04 01:11 UTC
Labels: bug, hash, error
