### ISSUE TITLE
prompt for feedback upon update

### ISSUE THREAD

**Issue by alltheseas** [zapstore/zapstore#110] opened 2024-06-28 15:16 UTC
upon app update (irregardless of auto or manual update)

1) prompt for update
2) if thumbs up -> prompt to zap  https://github.com/zapstore/zapstore/issues/70
3) if thumbs down -> specific app feedback & discussion #109

**Comment by franzaps** [comment] 2024-08-31 21:20
Duplicate of #109

**Closed by franzaps** 2024-08-31 21:20 UTC
Labels: design
